---
- name: Uninstall local projects
  hosts: local
  become: false
  gather_facts: true

  tasks:
    - name: Uninstall Excalidraw
      ansible.builtin.import_role:
        name: excalidraw
        tasks_from: uninstall
      tags:
        - excalidraw

    - name: Uninstall Open WebUI
      ansible.builtin.import_role:
        name: open_webui
        tasks_from: uninstall
      tags:
        - open_webui
