---
- name: Create assets directory
  ansible.builtin.file:
    path: "{{ homer_app_path }}/assets"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'

- name: Copy assets files
  ansible.builtin.copy:
    src: assets/
    dest: "{{ homer_app_path }}/assets/"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'

- name: Deploy Homer configuration
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ homer_app_path }}/assets/config.yml"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'

- name: Deploy Homer using common docker tasks
  ansible.builtin.include_role:
    name: common
    tasks_from: docker_app
  vars:
    common_app_install_path: "{{ homer_app_path }}"
    common_app_container_name: "{{ homer_container_name }}"
    common_app_image: "{{ homer_image }}"
    common_app_version: "{{ homer_image_version }}"
    common_app_ports:
      - "{{ homer_port }}:8080"
    common_app_volumes:
      - "{{ homer_app_path }}/assets:/www/assets"
    common_app_environment:
      INIT_ASSETS: "0"
