---
- name: Restart Ollama containers
  block:
    - name: Stop Ollama containers gracefully
      community.docker.docker_compose_v2:
        project_src: "{{ ollama_app_path }}"
        state: absent

    - name: Start Ollama containers
      community.docker.docker_compose_v2:
        project_src: "{{ ollama_app_path }}"
        state: present
        pull: "{{ ollama_pull_policy }}"
        recreate: "{{ ollama_recreate_policy }}"
        wait: true
        wait_timeout: 60

    - name: Wait for Ollama API to be ready
      ansible.builtin.uri:
        url: "http://localhost:{{ ollama_api_port }}/api/version"
        method: GET
        status_code: 200
      register: ollama_health_restart
      until: ollama_health_restart.status == 200
      retries: 12
      delay: 5

- name: Update Ollama CLI
  block:
    - name: Remove existing CLI
      ansible.builtin.file:
        path: "{{ ollama_cli_path }}"
        state: absent
      become: true

    - name: Re-extract CLI from updated container
      ansible.builtin.include_tasks: extract_cli.yml

- name: Extract Ollama CLI from container
  block:
    - name: Check if CLI already exists and get version
      ansible.builtin.stat:
        path: "{{ ollama_cli_path }}"
      register: existing_cli

    - name: Get existing CLI version
      ansible.builtin.command: "{{ ollama_cli_path }} --version"
      register: existing_cli_version
      changed_when: false
      failed_when: false
      when: existing_cli.stat.exists

    - name: Get container version
      community.docker.docker_container_exec:
        container: "{{ ollama_container_name }}"
        command: /bin/ollama --version
      register: container_version
