---
- name: Create path for postgres
  ansible.builtin.file:
    path: "{{ postgres_app_path }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'

- name: Create pgdata directory
  ansible.builtin.file:
    path: "{{ postgres_app_path }}/pgdata"
    state: directory
    mode: '0755'
  become: true

- name: Copy init-multiple-dbs.sh file
  ansible.builtin.template:
    src: init-multiple-dbs.sh.j2
    dest: "{{ postgres_app_path }}/init-multiple-dbs.sh"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'

- name: Copy Docker Compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ postgres_app_path }}/docker-compose.yml"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0644'

- name: Stop and remove existing Docker Compose services
  ansible.builtin.shell: |
    cd {{ postgres_app_path }}
    docker compose down
  register: posgresql_compose_down
  changed_when: true

- name: Start Docker Compose services
  ansible.builtin.shell: |
    cd {{ postgres_app_path }}
    docker compose up -d
  register: posgresql_compose_up
  changed_when: true
